# Generated by Django 5.0.1 on 2024-01-29 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm_info',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.basemodel')),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
                ('moisture', models.IntegerField(blank=True)),
                ('temperature', models.IntegerField(blank=True)),
                ('light_intensity', models.IntegerField(blank=True)),
                ('humidity', models.IntegerField(blank=True)),
                ('soil_ph', models.IntegerField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core_app.basemodel',),
        ),
    ]
