# Generated by Django 4.2.9 on 2024-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_info',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm_info',
            name='light_intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm_info',
            name='moisture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm_info',
            name='soil_ph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm_info',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
