# Generated by Django 4.2.9 on 2024-01-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_farm_info_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_info',
            name='name',
            field=models.CharField(default='Famer1', max_length=30),
        ),
    ]
