# Generated by Django 5.0.1 on 2024-01-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AddField(
            model_name='updates',
            name='main_message',
            field=models.TextField(blank=True),
        ),
    ]
