# Generated by Django 4.2.9 on 2024-01-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='image',
            field=models.ImageField(upload_to='updates_images/'),
        ),
    ]
