# Generated by Django 5.0.1 on 2024-01-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodel',
            name='is_deleted',
        ),
    ]
