# Generated by Django 4.2.9 on 2024-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_creditunion_tutorialpoint_alter_updates_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
