# Generated by Django 4.2.9 on 2024-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_basemodel_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
