# Generated by Django 4.2.9 on 2024-01-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_basemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
